import pandas as pd
from datetime import datetime

def generate_trading_report():
    """Create markdown report for easy reading"""
    
    print("\n" + "="*50)
    print("GENERATING TRADING REPORT")
    print("="*50)
    
    try:
        watchlist = pd.read_csv('output/watchlist.csv')
        all_stocks = pd.read_csv('output/all_stocks_ranked.csv')
    except FileNotFoundError as e:
        print(f"❌ Could not load data: {e}")
        return
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    analysis_date = datetime.now().strftime('%d %B %Y')
    
    # Calculate summary stats
    strong_buy_count = len(all_stocks[all_stocks['RECOMMENDATION'] == 'STRONG_BUY'])
    buy_count = len(all_stocks[all_stocks['RECOMMENDATION'] == 'BUY'])
    hold_count = len(all_stocks[all_stocks['RECOMMENDATION'] == 'HOLD'])
    
    report = f"""# 📈 NSE Momentum + Daily Volatility (E) Watchlist
**Generated:** {timestamp} IST  
**Analysis Date:** {analysis_date}

---

## 🎯 Strategy Logic

| Component | Weight | Description |
|-----------|--------|-------------|
| **Price Momentum** | 35% | Today's close vs previous close |
| **Intraday Strength** | 20% | Close vs Open (buying pressure) |
| **Range Breakout** | 15% | Closing near day's high |
| **Volume** | 15% | Higher than average volume |
| **Daily Volatility (E)** | 15% | Current day underlying daily volatility |

> **Note:** We use `Current Day Underlying Daily Volatility (E)` which represents today's estimated daily volatility.

---

## 🔥 Top 10 Momentum Stocks for Tomorrow

| # | Symbol | Close (₹) | Price Change % | Daily Vol (E) | Score | Action |
|---|--------|-----------|----------------|---------------|-------|--------|
"""

    for idx, row in watchlist.head(10).iterrows():
        symbol = row.get('SYMBOL', 'N/A')
        close = row.get('CLOSE_PRICE', 0)
        price_change = row.get('MOMENTUM_PRICE', 0) if 'MOMENTUM_PRICE' in row else 0
        daily_vol = row.get('VOLATILITY_DAILY', 0) if 'VOLATILITY_DAILY' in row else 0
        score = row.get('FINAL_SCORE', 0)
        rec = row.get('RECOMMENDATION', 'HOLD')
        
        vol_percent = daily_vol * 100 if daily_vol < 1 else daily_vol
        
        report += f"| {idx+1} | **{symbol}** | {close:.2f} | {price_change:+.2f}% | {vol_percent:.2f}% | {score:.0f} | {rec} |\n"
    
    report += f"""

---

## 📊 Summary Statistics

| Metric | Value |
|--------|-------|
| Total Equity Stocks Analyzed | {len(all_stocks):,} |
| **STRONG_BUY** Candidates | {strong_buy_count} |
| **BUY** Candidates | {buy_count} |
| **HOLD** Candidates | {hold_count} |

---

## 📈 High Volatility Confirmation (Top 5)

Stocks with significant daily volatility from watchlist:

"""

    if 'VOLATILITY_DAILY' in all_stocks.columns and len(watchlist) > 0:
        high_vol_watchlist = watchlist.nlargest(5, 'VOLATILITY_DAILY')
        
        for idx, row in high_vol_watchlist.iterrows():
            vol_val = row.get('VOLATILITY_DAILY', 0)
            vol_percent = vol_val * 100 if vol_val < 1 else vol_val
            report += f"- **{row.get('SYMBOL', 'N/A')}**: Daily Vol {vol_percent:.2f}% (Momentum Score: {row.get('FINAL_SCORE', 0):.0f})\n"
    else:
        report += "No high volatility stocks in watchlist\n"

    report += f"""

---

## 📋 How to Use This Report

1. **STRONG_BUY (Score > 75)**: High momentum + good volatility - consider for next day
2. **BUY (Score 60-75)**: Positive momentum - watch for entry
3. **HOLD (Score 40-60)**: Consolidating - wait for breakout
4. **Daily Volatility (E)**: Higher values (>3%) suggest genuine price expansion

---

## ⚠️ Disclaimer

This is an **automated scan** based on:
- NSE Bhavcopy (Price, Volume data)
- NSE Daily Volatility Report - **Current Day Underlying Daily Volatility (E)**

**Always do your own research** before trading. Past performance does not guarantee future results.

---
*Generated by NSE Automated Scanner*  
*Next run: Tomorrow at 7:40 PM IST*
"""
    
    # Save report
    with open('output/daily_report.md', 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"✅ Trading report generated: output/daily_report.md")
    print(f"   Watchlist contains {len(watchlist)} stocks")
    
    # Also generate a simple CSV with volatility info
    if len(watchlist) > 0 and 'VOLATILITY_DAILY' in watchlist.columns:
        watchlist[['SYMBOL', 'CLOSE_PRICE', 'MOMENTUM_PRICE', 'VOLATILITY_DAILY', 'FINAL_SCORE', 'RECOMMENDATION']].to_csv('output/watchlist_with_vol.csv', index=False)
        print(f"   Watchlist with volatility saved: output/watchlist_with_vol.csv")

if __name__ == "__main__":
    generate_trading_report()
