import pandas as pd
from datetime import datetime

def safe_float_convert(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return 0.0

def generate_trading_report():
    print("\n" + "="*50)
    print("GENERATING TRADING REPORT")
    print("="*50)
    
    try:
        all_stocks = pd.read_csv('output/all_stocks_ranked.csv')
        buy_watchlist = pd.read_csv('output/top_30_buy_watchlist.csv')
        top10 = pd.read_csv('output/top_10_momentum.csv')
    except FileNotFoundError as e:
        print(f"❌ Could not load data: {e}")
        return
    
    now = datetime.now()
    timestamp_str = now.strftime('%Y%m%d_%H%M%S')
    date_str = now.strftime('%d %B %Y')
    time_str = now.strftime('%H:%M:%S')
    
    md_filename = f"output/nifty200_momentum_report_{timestamp_str}.md"
    
    strong_buy = len(all_stocks[all_stocks['RECOMMENDATION'] == 'STRONG_BUY'])
    buy = len(all_stocks[all_stocks['RECOMMENDATION'] == 'BUY'])
    hold = len(all_stocks[all_stocks['RECOMMENDATION'] == 'HOLD'])
    
    report = f"""# 📈 NIFTY 200 Momentum Report
**Generated:** {date_str} at {time_str} IST  
**Report ID:** {timestamp_str}

---

## 🎯 Strategy Overview

| Component | Weight | Description |
|-----------|--------|-------------|
| Price Momentum | 35% | Today's close vs previous close |
| Intraday Strength | 20% | Close vs Open (buying pressure) |
| Range Breakout | 15% | Closing near day's high |
| Volume Momentum | 15% | Higher than average volume |
| Daily Volatility | 15% | Price expansion confirmation |

---

## 📊 Market Summary

| Metric | Value |
|--------|-------|
| **Nifty 200 Stocks Analyzed** | {len(all_stocks)} |
| **Analysis Date** | {date_str} |

### 📈 BUY Side Signals
| Recommendation | Count |
|---------------|-------|
| **STRONG_BUY** (Score > 75) | {strong_buy} |
| **BUY** (Score 60-75) | {buy} |
| **HOLD** (Score 40-60) | {hold} |

---

## 🔥 TOP 10 BUY CANDIDATES

| # | Symbol | Close (₹) | Change % | Daily Vol | Score | Action |
|---|--------|----------|----------|-----------|-------|--------|
"""
    
    for idx, row in top10.iterrows():
        symbol = row.get('SYMBOL', 'N/A')
        close = safe_float_convert(row.get('CLOSE_PRICE', 0))
        change = safe_float_convert(row.get('MOMENTUM_PRICE', 0))
        vol = safe_float_convert(row.get('VOLATILITY_DAILY', 0)) * 100
        score = safe_float_convert(row.get('FINAL_SCORE', 0))
        rec = row.get('RECOMMENDATION', 'HOLD')
        report += f"| {idx+1} | **{symbol}** | {close:.2f} | {change:+.2f}% | {vol:.2f}% | {score:.0f} | {rec} |\n"
    
    report += f"""

---

## 📋 Next 20 Stocks (11-30)

| # | Symbol | Change % | Score | Action |
|---|--------|----------|-------|--------|
"""
    
    for idx, row in buy_watchlist.iloc[10:30].iterrows():
        if idx < 30:
            symbol = row.get('SYMBOL', 'N/A')
            change = safe_float_convert(row.get('MOMENTUM_PRICE', 0))
            score = safe_float_convert(row.get('FINAL_SCORE', 0))
            rec = row.get('RECOMMENDATION', 'HOLD')
            report += f"| {idx+1} | {symbol} | {change:+.2f}% | {score:.0f} | {rec} |\n"
    
    report += f"""

---

## 📋 How to Use This Report

1. **STRONG_BUY (Score > 75)**: High conviction - consider for next day
2. **BUY (Score 60-75)**: Positive momentum - watch for entry
3. **HOLD (Score 40-60)**: Consolidating - wait for breakout

### Entry Strategy
- Look for opening price near previous day's close
- Consider entry on retracement to support levels
- Use volatility-based stop losses

---

## ⚠️ Disclaimer

This is an **automated scan** based on NSE data. Always perform your own research before trading.

---
*Generated by NSE Nifty 200 Momentum Scanner*
*Next run: Tomorrow at 7:40 PM IST*
"""
    
    with open(md_filename, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"✅ Timestamped report: {md_filename}")
    print(f"   BUY watchlist: {len(buy_watchlist)} stocks")
    
    with open('output/nifty200_momentum_report_latest.md', 'w', encoding='utf-8') as f:
        f.write(report)
    print(f"   Latest report: output/nifty200_momentum_report_latest.md")

if __name__ == "__main__":
    generate_trading_report()
